title: Flightradar Flight Card Dev
views:
  - title: Card Testing
    path: testing
    icon: mdi:airplane
    cards:
      - type: markdown
        content: |
          # Flightradar Flight Card Testing
          Use the controls below to simulate different flight states and test the card.

      - type: tile
        entity: input_select.payload_test_options
        features_position: bottom
        vertical: false
        features:
          - type: select-options

      - type: custom:flightradar-flight-card
        entity: sensor.payload
